name: Build and publish electron app

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build_for_linux:
    name: Build for linux
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install dependencies
        run: |
          rm -rf dist/
          npm install -g @quasar/cli yarn --force
          yarn install
      - name: Build and release Linux binaries
        env:
          EP_GH_IGNORE_TIME: true
          GH_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
        run: |
          quasar build --mode electron --publish always -T linux
  build_for_windows:
    name: Build for windows
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install dependencies
        run: |
          rm -rf dist/
          npm install -g @quasar/cli yarn --force
          yarn install
      - name: Install wine
        run: |
          sudo dpkg --add-architecture i386
          sudo apt update
          sudo apt install -y wine32
          sudo snap install snapcraft --classic
      - name: Build and release Windows binaries 
        env:
          EP_GH_IGNORE_TIME: true
          GH_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
        run: |
          quasar build --mode electron --publish always -T win32
  build_for_macos:
    name: Build for macos
    runs-on: macos-12
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install dependencies
        run: |
          rm -rf dist/
          npm install -g @quasar/cli yarn --force
          yarn install
      - name: dmg-license add
        run: |
          sudo npm install -g dmg-license
      - name: Build and release MacOS binaries
        env:
          EP_GH_IGNORE_TIME: true
          GH_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
        run: |
          quasar build --mode electron --publish always -T darwin